/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/domain/CompositePk.cpk.vm.java
 */
package org.visitor.appportal.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

@Embeddable
public class ProductSiteRecommendPk implements Comparable<ProductSiteRecommendPk>, Serializable {
    static final private long serialVersionUID = 1L;

    //--------------------------------------------
    // Primary key columns
    //--------------------------------------------
    private Long productId;
    private Integer siteId;

    public ProductSiteRecommendPk() {
    }

    public ProductSiteRecommendPk(Long productId, Integer siteId) {
        this.productId = productId;
        this.siteId = siteId;
    }

    /**
     * Helper to determine if this composite primary key can be considered as set or not.
     */
    @Transient
    public boolean isProductSiteRecommendPkSet() {
        return isProductIdSet() && isSiteIdSet();
    }

    /**
     * Helper method to determine if this instance is considered empty, that is,
     * if all the non primary key columns are null.
     */
    @Transient
    public boolean isEmpty() {
        return !isProductIdSet() && !isSiteIdSet();
    }

    //--------------------------------------------
    // Getters & Setters
    //--------------------------------------------

    //-- [productId] ------------------------------

    @Column(name = "product_id", nullable = false, precision = 20, insertable = false, updatable = false)
    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Helper method to set the productId attribute via an int.
     * @see #setProductId(Long)
     */
    public void setProductId(int productId) {
        this.productId = Long.valueOf(productId);
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isProductIdSet() {
        return getProductId() != null;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    
    //-- [siteId] ------------------------------

    @Column(name = "site_id", nullable = false, precision = 10, insertable = false, updatable = false)
    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isSiteIdSet() {
        return getSiteId() != null;
    }

    //-----------------------------------------------
    // equals & hashCode
    //-----------------------------------------------

    @Override
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }

        if (!(object instanceof ProductSiteRecommendPk)) {
            return false;
        }

        ProductSiteRecommendPk other = (ProductSiteRecommendPk) object;
        return new EqualsBuilder().append(getProductId(), other.getProductId()).append(getSiteId(), other.getSiteId()).isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37).append(getProductId()).append(getSiteId()).toHashCode();
    }

    //-----------------------------------------------
    // Comparable
    //-----------------------------------------------

    public int compareTo(ProductSiteRecommendPk other) {
        return new CompareToBuilder().append(getProductId(), other.getProductId()).append(getSiteId(), other.getSiteId()).toComparison();
    }

    //-----------------------------------------------
    // toString / from String
    //-----------------------------------------------

    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();

        if (isProductIdSet()) {
            result.append(getProductId());
        }
        
        result.append(":");

        if (isSiteIdSet()) {
            result.append(getSiteId());
        }

        return result.toString();
    }

    /**
     * Build an instance from a string version.
     */
    public static ProductSiteRecommendPk fromString(String string) {
        ProductSiteRecommendPk result = new ProductSiteRecommendPk();
        String[] values = string.split(":");
        if (values[0] != null && values[0].length() > 0) {
            result.setProductId(new Long(values[0]));
        }
        if (values[1] != null && values[1].length() > 0) {
            result.setSiteId(new Integer(values[1]));
        }
        return result;
    }
}
